name: Notify Client on Schema Change

on:
  push:
    paths:
      - 'README.md' # Update this to the path where your schema is stored

jobs:
  notify-client:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Client Repo Schema Update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CLIENT_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/slobicabobica/fe-test/dispatches \
            -d '{"event_type": "schema-change", "client_payload": {}}'

      - name: Set Pending Status on Backend PR
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{
              "state": "pending",
              "context": "Client Compatibility Check",
              "description": "Client compatibility check is running..."
            }'
