name: Notify Client on Schema Change

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  notify-client:
    runs-on: ubuntu-latest

    steps:
      - name: Check if README.md has changed
        id: check_readme
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'README.md'; then
            echo "README.md has changed"
            echo "::set-output name=readme_changed::true"
          else
            echo "README.md has not changed"
            echo "::set-output name=readme_changed::false"
          fi
    
      - name: Trigger Client Repo Schema Update
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CLIENT_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/slobicabobica/fe-test/dispatches \
            -d '{"event_type": "schema-change", "client_payload": {}}'

      - name: Set Pending Status on Backend PR
        if: github.event_name == 'pull_request' && steps.check_readme.outputs.readme_changed == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \     
            -d '{
              "state": "pending",
              "context": "Client Compatibility Check",
              "description": "Client compatibility check is running..."
            }'
      - name: Do something else if it's not a pull request
        if: github.event_name == 'pull_request'
        run: echo "This is not a pull request. ${{ github.event_name }}"
