name: Notify Client on Schema Change

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  notify-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # Fetch only the last two commits for comparison
       # Fetch the latest commit from the main branch
      - name: Fetch latest commit from main branch
        run: |
          git fetch origin main
          MAIN_COMMIT=$(git rev-parse origin/main)
          echo "Main branch commit: $MAIN_COMMIT"
          echo "main_commit=$MAIN_COMMIT" >> $GITHUB_ENV
      # Log the current commit SHA for debugging purposes
      - name: Log Current Commit SHA
        run: |
          echo "Current commit SHA: ${{ github.sha }}"  
      - name: Check if README.md content has changed
        id: check_readme
        run: |
          if git diff ${{ env.main_commit }} ${{ github.sha }} -- README.md | grep -q '^[-+]'; then
            echo "README.md has changed"
            echo "readme_changed=true" >> $GITHUB_ENV
          else
            echo "README.md has not changed"
            echo "readme_changed=false" >> $GITHUB_ENV
          fi
       # Get the current branch name from the backend
      - name: Get Branch Name
        run: echo "BE_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
        
      - name: Trigger Client Repo Schema Update
        if: env.readme_changed == 'true'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.CLIENT_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/slobicabobica/fe-test/dispatches \
            -d '{"event_type": "schema-change", "client_payload": {  "branch_name": "${{ env.BE_BRANCH }}" }}'

      - name: Set Pending Status on Backend PR
        if: env.readme_changed == 'true'
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d  '{
              "state": "pending",
              "context": "Client Compatibility Check",
              "description": "Client compatibility check is running..."
            }'
      - name: Set Success Status on Backend PR
        if: env.readme_changed == 'false'
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d  '{
              "state": "success",
              "context": "Client Compatibility Check",
              "description": "Client compatibility check is running..."
            }'        

